version: '3.5'
services:
  db:
    image: postgres:14.2-alpine
    restart: always
    env_file:
      - postgresql/db.env
    ports:
      - "5434:5432"
    networks:
      - employee-network
  swagger-ui:
    build: swagger-ui
    image: employee_swagger-ui:1.0.0
    ports:
      - "81:8080"

networks:
  employee-network:
    name: employee-network