database:
  url: jdbc:postgresql://localhost:5434/%s
  name: employee
  username: toukach
  password: clevertec
  driver: org.postgresql.Driver
  changeLogFile: db/migration/liquibase/changelog.xml
  liquibaseSchema: liquibase
  migrationEnable: true
cache:
  size: 3
  algorithm: LRU
print:
  outDirectory: file
  fontFilePath: document/pdf/font/Alice-Regular.ttf
  templateFilePath: document/pdf/template/Clevertec_Template.pdf